- name: NowSecure 
  uses: nowsecure/nowsecure-action@v1 

name: NowSecure Scan 
on: 
  push: 
    branches: 
      - main 
jobs: 
  nowsecure_scan: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2 
      - name: Set up JDK 
        uses: actions/setup-java@v2 
        with: 
          java-version: '11' 
      - name: Build and test 
        run: | 
          ./gradlew build 
     - id: upload 
      name: NowSecure upload app 
      uses: nowsecure/nowsecure-action/upload-app@v3 
      with: 
        platform_token: ${{ secrets.NS_TOKEN }} 
        app_file: "app/build/outputs/apk/debug/app-debug.apk" 
        # TODO: Replace the Group ID. 
        group_id: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" 