name: Detox Tests 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ] 

jobs: 
  test: 
    runs-on: ubuntu-latest 

    steps: 
      - uses: actions/checkout@v2 

      - name: Install Node.js 
        uses: actions/setup-node@v2 
        with: 
          node-version: '14.x' 

      - name: Install Detox CLI 
        run: npm install -g detox-cli 

      - name: Build and test 
        run: | 
          npm install 
          npx detox build --configuration android.emu.debug 
          npx detox test --configuration android.emu.debug 