scripts: 
    - name: iOS test 
      script: |  
        xcode-project run-tests \ 
          --workspace MyAwesomeApp.xcworkspace \ 
          --scheme MyAwesomeApp \ 
          --device "iPhone 11" 
    test_report: build/ios/test/*.xml 