
name: Android CI/CD 
on: 
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - main 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 
    - name: Set up JDK 
      uses: actions/setup-java@v2 
      with: 
        distribution: 'adopt' 
        java-version: 11 
    - name: Build with Gradle 
      run: ./gradlew build 
    - name: Run Unit Tests 
      run: ./gradlew test 
    - name: Generate AAB 
      run: ./gradlew bundleRelease 

    - name: Upload AAB to Google Play Store 
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
      uses: r0adkll/upload-google-play@v1 
      with: 
        serviceAccountJson: ${{ secrets.GOOGLE_PLAY_STORE_SERVICE_ACCOUNT_JSON }} 
        packageName: your.package.name 
        releaseFiles: app/build/outputs/bundle/release/app-release.aab 
        track: internal