workflows: 

  android-workflow: 
    name: Android Workflow 
    max_build_duration: 120 
    environment: 
      flutter: stable 
    scripts: 
      - name: Get Flutter packages 
        script: | 
          flutter packages pub get 
      - name: Flutter analyze 
        script: | 
          flutter analyze 
      - name: Flutter unit tests 
        script: | 
          flutter test 
        ignore_failure: true 
      - name: Build AAB with Flutter 

        script: | 

          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))       

          flutter build appbundle --release \ 

            --build-name=1.0.$BUILD_NUMBER \ 

            --build-number=$BUILD_NUMBER 

    artifacts: 

      - build/**/outputs/**/*.aab 

      - build/**/outputs/**/mapping.txt 

      - flutter_drive.log 

    publishing: 

      email: 

        recipients: 

          - user_1@example.com 

          - user_2@example.com 

        notify: 

          success: true 

          failure: false 

  ios-workflow: 

    name: iOS Workflow 

    max_build_duration: 120 

    environment: 

      flutter: stable 

      xcode: latest 

      cocoapods: default 

    scripts: 

      - name: Get Flutter packages 

        script: | 

          flutter packages pub get 

      - name: Install pods 

        script: | 

          find . -name "Podfile" -execdir pod install \; 

      - name: Flutter analyze 

        script: | 

          flutter analyze 

      - name: Flutter unit tests 

        script: | 

          flutter test 

        ignore_failure: true 

    artifacts: 

      - build/ios/ipa/*.ipa 

      - /tmp/xcodebuild_logs/*.log 

      - flutter_drive.log 

    publishing: 

      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email 

      email: 
        recipients: 
          - user_1@example.com 
          - user_2@example.com 
        notify: 
          success: true # To receive a notification when a build succeeds 
          failure: false # To not receive a notification when a build fails 